### ISSUE TITLE
Fix bug with tr_pointer.

### ISSUE THREAD

**Issue by Chenger1** [Chenger1/stellaris-trpack#44]
Either tr_pointer is saves wrong or continuing translation has a problem with skipping empty lines ('/n') symbol

**Comment by Chenger1** [comment]
Also, there is a problem with translating string at all. Opening new file through collection window doesn`t make right parsing and transfering text into translator.

**Comment by Chenger1** [comment]
Problem can be with translator seed

**Comment by Letiso** [comment]
Somehow it was fixed
