### ISSUE TITLE
Need fix bug when opening mod from collection that's below in stack

### ISSUE THREAD

**Issue by Letiso** [Chenger1/stellaris-trpack#59]
Accept window in this case doesn't closes by clicking confirm button

**Comment by Letiso** [comment]
There's other situation outside of stack 

(but doesn't matter coz it's connected with stack any way), 

when opening AcceptWindow, closing it and reopening it with confirmation doesn't closes AcceptWindow.

Maybe it's connected

**Comment by Chenger1** [comment]
Done
